logging:
  level:
    io.github.ppzxc.template: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    driver-class-name: org.postgresql.Driver
    username: template
    password: changeme
  jooq:
    sql-dialect: POSTGRES
