spring:
  application:
    name: template-api
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true

logging:
  structured:
    format:
      console: logstash

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when-authorized
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:}

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /v3/api-docs
