security:
  jwt:
    hmac-secret: test-jwt-secret-for-testing-purposes-only-not-used-in-production

spring:
  docker:
    compose:
      enabled: false
management:
  tracing:
    sampling:
      probability: 0.0
